### ISSUE TITLE
Version prefix is removed from Git tag and release name on release

### ISSUE THREAD

**Issue by adamkudrna** [JamesMGreene/node-draft-releaser#286]
I'm using this action [in my workflow](https://github.com/react-ui-org/react-ui/blob/master/.github/workflows/release-management.yml#L70) and it behaves sort of unexpectedly to me.

```yml
      - name: Publish matching GitHub release draft
        id: github_release
        uses: JamesMGreene/node-draft-releaser@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allow_release_name_update: 'false'
```

While the Release Drafter action drafts new releases correctly with the `v` prefix, eg. `v0.36.0`, the prefix is suddenly removed when `node-draft-releaser` publishes the release draft, both in the release name and in the Git tag.

I'm not sure if I'm missing something or a get the options wrong but I'd expect the release name and tag to remain intact.

I tried to turn off the `allow_release_name_update` option but with no effect.

Could anyone please point me to a solution?
